sistema: si3_internacao
tipo: desktop
runner: opencv

ambientes:
  dev:
    url: ''
    confidence: 0.75

credenciais:
  usuario: ${SI3_USER}
  senha: ${SI3_PASS}

dados_faker:
  - campo: paciente_id
    tipo: fixo
    valor: ${SI3_PACIENTE_ID}

  - campo: obs
    tipo: fixo
    valor: 'Teste realizado com ferramenta de automacao VTAE'

  - campo: unidade_funcional
    tipo: fixo
    valor: 'SC AMBULATORIO'

  - campo: provedor
    tipo: fixo
    valor: 'SUS'

  - campo: plano
    tipo: fixo
    valor: 'SUS'

  - campo: origem_tipo
    tipo: fixo
    valor: 'RESIDENCIA'

  - campo: matricula_responsavel
    tipo: fixo
    valor: '1'

  - campo: numero_compl
    tipo: fixo
    valor: '1'

  - campo: localizar_medico
    tipo: fixo
    valor: 'informatica'